remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  
logo: /assets/img/logo.png

title: "Clases de Bioestadística"
description: "Portal de materiales de la asignatura<br>Grado en Genética (UAB)"
