---
  class: animated, fadeIn

### Comprobar si los datos siguen una distribución normal

.pull-left[
  **QQ-plot**
    - Método gráfico para comparar dos distribuciones de probabilidad a través de sus cuantiles.  
  - Si las distribuciones son similares, los puntos caen cerca de la línea $y=x$.  
  - Se utiliza principalmente para comprobar si los datos siguen una distribución normal.
  
]
.pull-right[
  **Test de Shapiro–Wilk**
    - Suposición base (hipótesis nula): los datos se distribuyen de manera normal.  
  - Si el test es significativo (*p* < 0.05), los datos no siguen una distribución normal.  
  - Muy sensible al tamaño de muestra: con muestras grandes puede detectar desviaciones muy pequeñas de la normalidad, mientras que con muestras pequeñas puede no detectar desviaciones importantes.
]

---
  class: animated, fadeIn

#### Test de Shapiro-Wilk en `R`

.pull-left[
  
  ```{r}
  set.seed(10)
  vector_normal <- rnorm(n = 5000, 
                         mean = 20, sd = 2)
  shapiro.test(vector_normal)
  ```
  
  ```{r, echo = F, fig.height=3, fig.width=3, fig.align='center'}
  ggplot(data.frame(x=vector_normal), aes(sample=x)) +
    stat_qq(color="cadetblue4") +
    stat_qq_line(color="firebrick4") +
    labs(title="QQ-plot",
         x="Cuantiles teóricos",
         y="Cuantiles muestrales") +
    ggthemes::theme_base(base_size = 13) +
    theme(panel.grid=element_blank(),
          axis.text=element_text(color="black"),
          panel.background = element_rect(fill = "white"))
  
  
  ```
  
  
  - Datos distribuidos de manera normal
  
]

.pull-right[
  
  
  ```{r}
  set.seed(10)
  vector_exp <- rexp(n = 500, 
                     rate = 0.5) 
  shapiro.test(vector_exp)
  ```
  
  ```{r, echo = F, fig.height=3, fig.width=3, fig.align='center'}
  
  ggplot(data.frame(x=vector_exp), aes(sample=x)) +
    stat_qq(color="cadetblue4") +
    stat_qq_line(color="firebrick4") +
    labs(title="QQ-plot",
         x="Cuantiles teóricos",
         y="Cuantiles muestrales") +
    ggthemes::theme_base(base_size = 13) +
    theme(panel.grid=element_blank(),
          axis.text=element_text(color="black"),
          panel.background = element_rect(fill = "white"))
  
  
  
  ```
  
  - Datos no distribuidos de manera normal
  
]


---
  class: animated, fadeIn

#### Test de Shapiro-Wilk en `R`

.pull-left[
  
  ```{r}
  set.seed(10)
  vector_normal <- rnorm(n = 5000, 
                         mean = 20, sd = 2)
  shapiro.test(vector_normal)
  ```
  
  
  ```{r, echo = F, fig.height=3, fig.width=3, fig.align='center'}
  
  data <- data.frame(norm = vector_normal)
  
  # Definir el ancho del bin
  binwidth <- 0.5
  
  # Crear histograma con curva de densidad ajustada (counts)
  ggplot(data, aes(x = norm)) +
    geom_histogram(color = "black", fill = "cadetblue4",
                   binwidth = binwidth, bins = 10) +
    labs(
      x = "x",
      y = "Counts"
    ) +
    ggthemes::theme_base(base_size = 13) +
    theme(panel.grid=element_blank(),
          axis.text=element_text(color="black"),
          panel.background = element_rect(fill = "white"))
  
  
  ```
  
  
  - Datos distribuidos de manera normal
  
]

.pull-right[
  
  
  ```{r}
  set.seed(10)
  vector_exp <- rexp(n = 500, 
                     rate = 0.5) 
  shapiro.test(vector_exp)
  ```
  
  ```{r, echo = F, fig.height=3, fig.width=3, fig.align='center'}
  
  data <- data.frame(exp = vector_exp)
  
  # Crear histograma con curva de densidad ajustada (counts)
  ggplot(data, aes(x = exp)) +
    geom_histogram(color = "black", fill = "cadetblue4",
                   binwidth = binwidth, bins = 10) +
    labs(
      x = "x",
      y = "Counts"
    ) +
    ggthemes::theme_base(base_size = 13) +
    theme(panel.grid=element_blank(),
          axis.text=element_text(color="black"),
          panel.background = element_rect(fill = "white"))
  
  ```
  
  - Datos no distribuidos de manera normal
  
]
